"use client";

import { useState } from "react";
import { QRCodeCanvas } from "qrcode.react";
import { Download, X, Type } from "lucide-react";

export default function QRCodeModal({ url, onClose }: { url: string; onClose: () => void }) {
    // Extract the alias from the URL to use as the default title
    const defaultAlias = url.split('/').pop() || "SCAN ME";
    const [title, setTitle] = useState(defaultAlias.toUpperCase());

    const handleDownload = () => {
        // 1. Get the raw QR code canvas generated by qrcode.react
        const qrCanvas = document.getElementById("qr-canvas") as HTMLCanvasElement;
        if (!qrCanvas) return;

        // 2. Create a new "Master" canvas in memory to combine everything
        const finalCanvas = document.createElement("canvas");
        const ctx = finalCanvas.getContext("2d");
        if (!ctx) return;

        // Layout settings for the downloaded image
        const padding = 40;
        const textSpace = title ? 50 : 0;
        const qrSize = 256; // High-res QR size

        finalCanvas.width = qrSize + (padding * 2);
        finalCanvas.height = qrSize + (padding * 2) + textSpace;

        // 3. Draw a clean white background (required for scannability)
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, finalCanvas.width, finalCanvas.height);

        // 4. Draw the custom title
        if (title) {
            ctx.fillStyle = "#000000";
            ctx.font = "bold 28px system-ui, -apple-system, sans-serif";
            ctx.textAlign = "center";
            ctx.textBaseline = "top";
            ctx.fillText(title, finalCanvas.width / 2, padding);
        }

        // 5. Draw the QR code below the title
        const qrYOffset = padding + textSpace;
        ctx.drawImage(qrCanvas, padding, qrYOffset, qrSize, qrSize);

        // 6. Convert to PNG and trigger browser download
        const pngUrl = finalCanvas.toDataURL("image/png");
        const downloadLink = document.createElement("a");
        downloadLink.href = pngUrl;
        downloadLink.download = `link-monowar-${defaultAlias}.png`;
        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-white/80 dark:bg-black/80 p-4 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="w-full max-w-sm rounded-2xl border border-slate-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-6 shadow-2xl">

                {/* Header */}
                <div className="mb-6 flex items-center justify-between">
                    <h3 className="text-xl font-bold text-slate-900 dark:text-white">QR Code Studio</h3>
                    <button onClick={onClose} className="rounded-lg p-2 text-slate-500 dark:text-neutral-400 hover:bg-neutral-200 dark:hover:bg-neutral-800 hover:text-slate-900 dark:hover:text-white transition-colors">
                        <X className="h-5 w-5" />
                    </button>
                </div>

                {/* Title Editor */}
                <div className="mb-6 group relative">
                    <Type className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-600 dark:text-slate-500 transition-colors group-focus-within:text-blue-500" />
                    <input
                        type="text"
                        value={title}
                        onChange={(e) => setTitle(e.target.value)}
                        placeholder="e.g., SCAN ME"
                        maxLength={20}
                        className="w-full rounded-xl border border-slate-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 py-3 pl-10 pr-4 text-sm font-bold text-slate-900 dark:text-white uppercase outline-none transition-all focus:border-blue-500/50"
                    />
                </div>

                {/* Live Preview Card */}
                <div className="mb-6 flex flex-col items-center justify-center overflow-hidden rounded-xl bg-neutral-900 dark:bg-white p-6 shadow-inner">
                    {title && (
                        <h4 className="mb-4 text-2xl font-bold tracking-tight text-white dark:text-black uppercase">
                            {title}
                        </h4>
                    )}
                    {/* We use QRCodeCanvas here so we can extract it for the download */}
                    <QRCodeCanvas
                        id="qr-canvas"
                        value={url}
                        size={200}
                        level="H" // High error correction (better for printing)
                        includeMargin={false}
                    />
                </div>

                <p className="mb-6 text-center text-xs text-slate-600 dark:text-slate-500 break-all">{url}</p>

                {/* Actions */}
                <div className="flex gap-3">
                    <button
                        onClick={onClose}
                        className="w-1/2 rounded-xl bg-neutral-100 dark:bg-neutral-800 px-4 py-3 text-sm font-medium text-slate-900 dark:text-white transition-colors hover:bg-neutral-300 dark:hover:bg-neutral-700"
                    >
                        Close
                    </button>
                    <button
                        onClick={handleDownload}
                        className="flex w-1/2 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-slate-900 dark:text-white transition-colors hover:bg-blue-500"
                    >
                        <Download className="h-4 w-4" />
                        Download
                    </button>
                </div>

            </div>
        </div>
    );
}