"use client";

import { useState, useEffect } from "react";
import {
    PlusCircle, BarChart3, Settings, QrCode, X, Download, Link2,
    Wifi, MapPin, Mail, Type, Palette, LayoutTemplate
} from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { QRCodeCanvas } from "qrcode.react";

type QrType = "url" | "text" | "wifi" | "email" | "location";
type QrVariant = "standard" | "framed";

export default function QuickActions() {
    const router = useRouter();

    // --- Modal & Configuration State ---
    const [isQrModalOpen, setIsQrModalOpen] = useState(false);
    const [qrType, setQrType] = useState<QrType>("url");
    const [qrVariant, setQrVariant] = useState<QrVariant>("framed");

    // --- QR Data States ---
    const [urlData, setUrlData] = useState("");
    const [textData, setTextData] = useState("");

    // Wi-Fi State
    const [wifiSsid, setWifiSsid] = useState("");
    const [wifiPass, setWifiPass] = useState("");
    const [wifiEncryption, setWifiEncryption] = useState("WPA");

    // Email State
    const [emailTo, setEmailTo] = useState("");
    const [emailSub, setEmailSub] = useState("");
    const [emailBody, setEmailBody] = useState("");

    // Location State
    const [locLat, setLocLat] = useState("");
    const [locLng, setLocLng] = useState("");

    // --- Styling State ---
    const [qrColor, setQrColor] = useState("#000000");
    const [qrBgColor, setQrBgColor] = useState("#ffffff");
    const [frameText, setFrameText] = useState("SCAN ME");

    // Dynamically update the frame text when the QR Type changes
    useEffect(() => {
        switch (qrType) {
            case "url": setFrameText("SCAN ME"); break;
            case "wifi": setFrameText("CONNECT WIFI"); break;
            case "text": setFrameText("READ MESSAGE"); break;
            case "email": setFrameText("SEND EMAIL"); break;
            case "location": setFrameText("FIND LOCATION"); break;
        }
    }, [qrType]);

    // --- Existing Quick Actions Logic ---
    const handleScrollToCreate = () => {
        const section = document.getElementById("create-link-section");
        section?.scrollIntoView({ behavior: "smooth" });
        setTimeout(() => {
            document.getElementById("originalUrlInput")?.focus();
        }, 500);
    };

    const handleExport = async () => {
        const loadingToast = toast.loading("Generating your CSV export...");
        try {
            const res = await fetch("/api/export");
            if (!res.ok) throw new Error("Export failed");

            const blob = await res.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `GoMono-export-${new Date().toISOString().split('T')[0]}.csv`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);

            toast.success("Export complete!", { id: loadingToast });
        } catch (error) {
            toast.error("Failed to export statistics.", { id: loadingToast });
        }
    };

    const handleSettings = () => {
        router.push("/dashboard/settings");
    };

    // --- QR Generation Logic ---
    const getQrPayload = () => {
        switch (qrType) {
            case "url": return urlData;
            case "text": return textData;
            case "wifi": return wifiSsid ? `WIFI:T:${wifiEncryption};S:${wifiSsid};P:${wifiPass};;` : "";
            case "email": return emailTo ? `mailto:${emailTo}?subject=${encodeURIComponent(emailSub)}&body=${encodeURIComponent(emailBody)}` : "";
            case "location": return (locLat && locLng) ? `geo:${locLat},${locLng}` : "";
            default: return "";
        }
    };

    const rawPayload = getQrPayload();

    const handleDownloadQR = async () => {
        if (!rawPayload) return;

        // 1. Get the base QR code canvas generated by qrcode.react
        const qrCanvas = document.getElementById("advanced-qr-canvas") as HTMLCanvasElement;
        if (!qrCanvas) return;

        if (qrVariant === "standard") {
            // Standard Download: Just download the raw QR canvas directly
            const pngUrl = qrCanvas.toDataURL("image/png");
            triggerDownload(pngUrl, `GoMono-${qrType.toUpperCase()}-QR.png`);
            toast.success("Standard QR Code downloaded!");
        } else {
            // Framed Download: Create a master canvas to draw the frame and text
            const masterCanvas = document.createElement("canvas");
            const ctx = masterCanvas.getContext("2d");
            if (!ctx) return;

            const qrSize = 500;
            const padding = 40;
            const textHeight = 100;

            // Set master canvas dimensions
            masterCanvas.width = qrSize + (padding * 2);
            masterCanvas.height = qrSize + (padding * 2) + textHeight;

            // Helper function to draw rounded rectangles
            const drawRoundedRect = (x: number, y: number, w: number, h: number, r: number, fill: string) => {
                ctx.fillStyle = fill;
                ctx.beginPath();
                ctx.moveTo(x + r, y);
                ctx.lineTo(x + w - r, y);
                ctx.quadraticCurveTo(x + w, y, x + w, y + r);
                ctx.lineTo(x + w, y + h - r);
                ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
                ctx.lineTo(x + r, y + h);
                ctx.quadraticCurveTo(x, y + h, x, y + h - r);
                ctx.lineTo(x, y + r);
                ctx.quadraticCurveTo(x, y, x + r, y);
                ctx.closePath();
                ctx.fill();
            };

            // 1. Draw the outer frame (Foreground Color)
            drawRoundedRect(0, 0, masterCanvas.width, masterCanvas.height, 40, qrColor);

            // 2. Draw the inner box for the QR (Background Color)
            const innerPadding = 15;
            drawRoundedRect(
                innerPadding,
                innerPadding,
                masterCanvas.width - (innerPadding * 2),
                qrSize + (padding * 2) - (innerPadding * 2),
                25,
                qrBgColor
            );

            // 3. Draw the actual QR Code on top of the inner box
            ctx.drawImage(qrCanvas, padding, padding, qrSize, qrSize);

            // 4. Draw the custom text at the bottom
            if (frameText) {
                ctx.fillStyle = qrBgColor; // Text color is the background color
                ctx.font = "bold 65px system-ui, -apple-system, sans-serif";
                ctx.textAlign = "center";
                ctx.textBaseline = "middle";
                ctx.fillText(frameText, masterCanvas.width / 2, masterCanvas.height - (textHeight / 2) - 10);
            }

            // 5. Convert and Download
            const pngUrl = masterCanvas.toDataURL("image/png");
            triggerDownload(pngUrl, `GoMono-${qrType.toUpperCase()}-Framed-QR.png`);
            toast.success("Framed QR Code downloaded!");
        }
    };

    const triggerDownload = (dataUrl: string, filename: string) => {
        const link = document.createElement("a");
        link.href = dataUrl;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const resetQrModal = () => {
        setIsQrModalOpen(false);
        setUrlData("");
        setTextData("");
        setWifiSsid("");
        setWifiPass("");
        setEmailTo("");
        setEmailSub("");
        setEmailBody("");
        setLocLat("");
        setLocLng("");
        setQrColor("#000000");
        setQrBgColor("#ffffff");
        setQrType("url");
        setQrVariant("framed");
    };

    return (
        <>
            {/* Quick Actions Grid */}
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {/* 1. Create Link */}
                <button
                    onClick={handleScrollToCreate}
                    className="flex items-center gap-3 rounded-xl border border-neutral-200 bg-white p-4 text-left shadow-sm transition-all hover:border-blue-500/50 hover:bg-blue-50 dark:border-neutral-800 dark:bg-neutral-900/50 dark:hover:border-blue-500/50 dark:hover:bg-blue-900/10"
                >
                    <div className="rounded-lg bg-blue-100 p-2 text-blue-600 dark:bg-blue-500/10 dark:text-blue-400">
                        <PlusCircle className="h-5 w-5" />
                    </div>
                    <span className="text-sm font-medium text-neutral-700 dark:text-neutral-300">Create Link</span>
                </button>

                {/* 2. QR Code Generator */}
                <button
                    onClick={() => setIsQrModalOpen(true)}
                    className="flex items-center gap-3 rounded-xl border border-neutral-200 bg-white p-4 text-left shadow-sm transition-all hover:border-purple-500/50 hover:bg-purple-50 dark:border-neutral-800 dark:bg-neutral-900/50 dark:hover:border-purple-500/50 dark:hover:bg-purple-900/10"
                >
                    <div className="rounded-lg bg-purple-100 p-2 text-purple-600 dark:bg-purple-500/10 dark:text-purple-400">
                        <QrCode className="h-5 w-5" />
                    </div>
                    <span className="text-sm font-medium text-neutral-700 dark:text-neutral-300">QR Studio</span>
                </button>

                {/* 3. Export Stats */}
                <button
                    onClick={handleExport}
                    className="flex items-center gap-3 rounded-xl border border-neutral-200 bg-white p-4 text-left shadow-sm transition-all hover:border-emerald-500/50 hover:bg-emerald-50 dark:border-neutral-800 dark:bg-neutral-900/50 dark:hover:border-emerald-500/50 dark:hover:bg-emerald-900/10"
                >
                    <div className="rounded-lg bg-emerald-100 p-2 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400">
                        <BarChart3 className="h-5 w-5" />
                    </div>
                    <span className="text-sm font-medium text-neutral-700 dark:text-neutral-300">Export Stats</span>
                </button>

                {/* 4. Settings */}
                <button
                    onClick={handleSettings}
                    className="flex items-center gap-3 rounded-xl border border-neutral-200 bg-white p-4 text-left shadow-sm transition-all hover:border-neutral-400 hover:bg-neutral-50 dark:border-neutral-800 dark:bg-neutral-900/50 dark:hover:border-neutral-500/50 dark:hover:bg-neutral-800"
                >
                    <div className="rounded-lg bg-neutral-100 p-2 text-neutral-600 dark:bg-neutral-800 dark:text-neutral-400">
                        <Settings className="h-5 w-5" />
                    </div>
                    <span className="text-sm font-medium text-neutral-700 dark:text-neutral-300">Settings</span>
                </button>
            </div>

            {/* Advanced QR Studio Modal */}
            {isQrModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/60 p-4 backdrop-blur-sm animate-in fade-in">
                    <div className="my-8 w-full max-w-lg rounded-2xl border border-neutral-200 bg-white p-6 shadow-2xl dark:border-neutral-800 dark:bg-neutral-950">
                        {/* Header */}
                        <div className="mb-6 flex items-center justify-between">
                            <h3 className="flex items-center gap-2 text-lg font-bold text-neutral-900 dark:text-white">
                                <QrCode className="h-5 w-5 text-purple-500" />
                                Advanced QR Studio
                            </h3>
                            <button
                                onClick={resetQrModal}
                                className="rounded-lg p-2 text-neutral-400 hover:bg-neutral-100 hover:text-neutral-900 dark:hover:bg-neutral-800 dark:hover:text-white transition-colors"
                            >
                                <X className="h-5 w-5" />
                            </button>
                        </div>

                        {/* QR Type Selector Tabs */}
                        <div className="mb-6 flex gap-2 overflow-x-auto pb-2 scrollbar-hide">
                            <button onClick={() => setQrType("url")} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors ${qrType === "url" ? "bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300" : "bg-neutral-100 text-neutral-600 hover:bg-neutral-200 dark:bg-neutral-900 dark:text-neutral-400 dark:hover:bg-neutral-800"}`}>
                                <Link2 className="h-4 w-4" /> URL
                            </button>
                            <button onClick={() => setQrType("wifi")} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors ${qrType === "wifi" ? "bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300" : "bg-neutral-100 text-neutral-600 hover:bg-neutral-200 dark:bg-neutral-900 dark:text-neutral-400 dark:hover:bg-neutral-800"}`}>
                                <Wifi className="h-4 w-4" /> Wi-Fi
                            </button>
                            <button onClick={() => setQrType("text")} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors ${qrType === "text" ? "bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300" : "bg-neutral-100 text-neutral-600 hover:bg-neutral-200 dark:bg-neutral-900 dark:text-neutral-400 dark:hover:bg-neutral-800"}`}>
                                <Type className="h-4 w-4" /> Text
                            </button>
                            <button onClick={() => setQrType("email")} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors ${qrType === "email" ? "bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300" : "bg-neutral-100 text-neutral-600 hover:bg-neutral-200 dark:bg-neutral-900 dark:text-neutral-400 dark:hover:bg-neutral-800"}`}>
                                <Mail className="h-4 w-4" /> Email
                            </button>
                            <button onClick={() => setQrType("location")} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors ${qrType === "location" ? "bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-300" : "bg-neutral-100 text-neutral-600 hover:bg-neutral-200 dark:bg-neutral-900 dark:text-neutral-400 dark:hover:bg-neutral-800"}`}>
                                <MapPin className="h-4 w-4" /> Location
                            </button>
                        </div>

                        {/* Dynamic Input Fields */}
                        <div className="mb-6 space-y-4">
                            {qrType === "url" && (
                                <input type="url" placeholder="https://example.com" value={urlData} onChange={(e) => setUrlData(e.target.value)} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all focus:border-purple-500/50 focus:ring-4 focus:ring-purple-500/10 dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                            )}

                            {qrType === "text" && (
                                <textarea rows={3} placeholder="Enter your text message here..." value={textData} onChange={(e) => setTextData(e.target.value)} className="w-full resize-none rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all focus:border-purple-500/50 focus:ring-4 focus:ring-purple-500/10 dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                            )}

                            {qrType === "wifi" && (
                                <div className="grid grid-cols-2 gap-3">
                                    <input type="text" placeholder="Network Name (SSID)" value={wifiSsid} onChange={(e) => setWifiSsid(e.target.value)} className="col-span-2 w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                                    <input type="text" placeholder="Password" value={wifiPass} onChange={(e) => setWifiPass(e.target.value)} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                                    <select value={wifiEncryption} onChange={(e) => setWifiEncryption(e.target.value)} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all dark:border-neutral-800 dark:bg-neutral-900 dark:text-white">
                                        <option value="WPA">WPA/WPA2</option>
                                        <option value="WEP">WEP</option>
                                        <option value="nopass">None</option>
                                    </select>
                                </div>
                            )}

                            {qrType === "email" && (
                                <div className="space-y-3">
                                    <input type="email" placeholder="Recipient Email" value={emailTo} onChange={(e) => setEmailTo(e.target.value)} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                                    <input type="text" placeholder="Subject" value={emailSub} onChange={(e) => setEmailSub(e.target.value)} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                                    <textarea rows={2} placeholder="Message Body..." value={emailBody} onChange={(e) => setEmailBody(e.target.value)} className="w-full resize-none rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                                </div>
                            )}

                            {qrType === "location" && (
                                <div className="grid grid-cols-2 gap-3">
                                    <input type="number" step="any" placeholder="Latitude (e.g. 40.7128)" value={locLat} onChange={(e) => setLocLat(e.target.value)} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                                    <input type="number" step="any" placeholder="Longitude (e.g. -74.0060)" value={locLng} onChange={(e) => setLocLng(e.target.value)} className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm outline-none transition-all dark:border-neutral-800 dark:bg-neutral-900 dark:text-white" />
                                </div>
                            )}
                        </div>

                        {/* Customization Options */}
                        <div className="mb-6 space-y-4 rounded-xl border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-800 dark:bg-neutral-900/50">

                            {/* Variant Toggle */}
                            <div className="flex items-center justify-between border-b border-neutral-200 pb-4 dark:border-neutral-800">
                                <div className="flex items-center gap-2">
                                    <LayoutTemplate className="h-4 w-4 text-neutral-500" />
                                    <span className="text-sm font-medium text-neutral-700 dark:text-neutral-300">Style</span>
                                </div>
                                <div className="flex rounded-lg bg-neutral-200/50 p-1 dark:bg-neutral-950">
                                    <button onClick={() => setQrVariant("standard")} className={`rounded-md px-3 py-1.5 text-xs font-medium transition-all ${qrVariant === "standard" ? "bg-white text-black shadow-sm dark:bg-neutral-800 dark:text-white" : "text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-white"}`}>Standard</button>
                                    <button onClick={() => setQrVariant("framed")} className={`rounded-md px-3 py-1.5 text-xs font-medium transition-all ${qrVariant === "framed" ? "bg-white text-black shadow-sm dark:bg-neutral-800 dark:text-white" : "text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-white"}`}>Framed</button>
                                </div>
                            </div>

                            {/* Colors */}
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-2">
                                    <Palette className="h-4 w-4 text-neutral-500" />
                                    <span className="text-sm font-medium text-neutral-700 dark:text-neutral-300">Colors</span>
                                </div>
                                <div className="flex items-center gap-4">
                                    <div className="flex items-center gap-2">
                                        <label className="text-xs text-neutral-500">QR / Frame</label>
                                        <input type="color" value={qrColor} onChange={(e) => setQrColor(e.target.value)} className="h-8 w-8 cursor-pointer rounded border-0 bg-transparent p-0" />
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <label className="text-xs text-neutral-500">Background</label>
                                        <input type="color" value={qrBgColor} onChange={(e) => setQrBgColor(e.target.value)} className="h-8 w-8 cursor-pointer rounded border-0 bg-transparent p-0" />
                                    </div>
                                </div>
                            </div>

                            {/* Frame Text Input (Only shows if Framed is selected) */}
                            {qrVariant === "framed" && (
                                <div className="flex items-center justify-between border-t border-neutral-200 pt-4 dark:border-neutral-800 animate-in fade-in slide-in-from-top-2">
                                    <div className="flex items-center gap-2">
                                        <Type className="h-4 w-4 text-neutral-500" />
                                        <span className="text-sm font-medium text-neutral-700 dark:text-neutral-300">Label</span>
                                    </div>
                                    <input
                                        type="text"
                                        value={frameText}
                                        onChange={(e) => setFrameText(e.target.value.toUpperCase())}
                                        placeholder="e.g. SCAN ME"
                                        maxLength={15}
                                        className="w-1/2 rounded-md border border-neutral-300 bg-white px-3 py-1.5 text-xs font-bold outline-none dark:border-neutral-700 dark:bg-neutral-950 dark:text-white uppercase"
                                    />
                                </div>
                            )}
                        </div>

                        {/* Hidden high-res canvas for downloading */}
                        <div className="hidden">
                            <QRCodeCanvas
                                id="advanced-qr-canvas"
                                value={rawPayload || "https://imono.bro.bd"}
                                size={500}
                                level="H"
                                fgColor={qrColor}
                                bgColor={qrBgColor}
                                includeMargin={false}
                            />
                        </div>

                        {/* Preview and Download */}
                        {rawPayload ? (
                            <div className="flex flex-col items-center gap-4 rounded-xl border border-neutral-200 bg-neutral-50 p-6 dark:border-neutral-800 dark:bg-neutral-900/50">

                                {/* Dynamic Preview Box */}
                                {qrVariant === "standard" ? (
                                    <div className="rounded-xl p-3 shadow-sm" style={{ backgroundColor: qrBgColor }}>
                                        <QRCodeCanvas
                                            value={rawPayload}
                                            size={150}
                                            level="H"
                                            fgColor={qrColor}
                                            bgColor={qrBgColor}
                                        />
                                    </div>
                                ) : (
                                    <div className="rounded-xl p-3 shadow-sm flex flex-col items-center" style={{ backgroundColor: qrColor }}>
                                        <div className="rounded-lg p-2" style={{ backgroundColor: qrBgColor }}>
                                            <QRCodeCanvas
                                                value={rawPayload}
                                                size={130}
                                                level="H"
                                                fgColor={qrColor}
                                                bgColor={qrBgColor}
                                            />
                                        </div>
                                        {frameText && (
                                            <div className="mt-2 text-center font-bold tracking-widest uppercase text-xs" style={{ color: qrBgColor }}>
                                                {frameText}
                                            </div>
                                        )}
                                    </div>
                                )}

                                <button
                                    onClick={handleDownloadQR}
                                    className="flex w-full items-center justify-center gap-2 rounded-xl bg-purple-600 py-3 text-sm font-medium text-white transition-colors hover:bg-purple-700"
                                >
                                    <Download className="h-4 w-4" />
                                    Download {qrVariant === "framed" ? "Framed " : ""}QR
                                </button>
                            </div>
                        ) : (
                            <div className="flex h-40 flex-col items-center justify-center rounded-xl border border-dashed border-neutral-300 bg-neutral-50 dark:border-neutral-800 dark:bg-neutral-900/30">
                                <QrCode className="mb-2 h-8 w-8 text-neutral-400" />
                                <p className="text-sm text-neutral-500">Fill in the fields above to preview</p>
                            </div>
                        )}
                    </div>
                </div>
            )}
        </>
    );


}